# Generated by Django 5.2.7 on 2025-10-14 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
